### ISSUE TITLE
Failed to find the storage node

### ISSUE THREAD

**Issue by bessieIsBinBIn** [hkbudb/slimchain#2]
when I run "./target/release/slimchain-node-tee -c config-example/raft.toml"

then run "./target/release/slimchain-send-tx -a 10 -r 100 -t 1000 cpuheavy"

occur the error "ERROR slimchain_network::behavior::raft::client_network: Failed to find the storage node. ShardId: ShardId { id: 0, total: 1 } tx_req_id=0x3ada…a38a"

then I try to config the file: copy the raft.toml and modify the "client" to "storage". And after I run "./target/release/slimchain-node-tee -c config-example/raft_storage.toml", occur "Error: Failed to make http request for intel report."

I don't know how to solve the problem. Please give us the example of building the network

**Comment by xu-cheng** [comment]
You need to create a proper network to test the software. The minimum network size when using raft is 4 nodes (3 consensus nodes + 1 storage node).

You also need to ensure each node has their proper config.toml, which assigns the proper role, ip, and port for each node. The config.toml should also contains the information to describe the entire network topology. The config_example in this repo is more to document the syntax of the configure file rather than what configure should be like in a real network.
